spring.datasource.url=jdbc:postgresql://db:5433/test_db
spring.datasource.username=test_user
spring.datasource.password=test_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true